"""initial

Revision ID: 19b84d5ae0e4
Revises: 
Create Date: 2026-03-29 23:54:47.673436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b84d5ae0e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('steam_id', sa.String(length=32), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('skin_name', sa.String(length=256), nullable=False),
    sa.Column('trade_offer_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('operation_type', sa.String(length=16), nullable=False),
    sa.Column('operation_id', sa.BigInteger(), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('steam_id', sa.String(length=32), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steam_id')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('steam_id', sa.String(length=32), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('skin_name', sa.String(length=256), nullable=False),
    sa.Column('trade_url', sa.String(length=512), nullable=False),
    sa.Column('trade_offer_id', sa.String(length=32), nullable=True),
    sa.Column('burn_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawals')
    op.drop_table('users')
    op.drop_table('trade_logs')
    op.drop_table('deposits')
    # ### end Alembic commands ###
